bookers2/config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users

  root :to => "homes#top"
  get "home/about" => "homes#about"
  get '/search' => 'search#search'

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # relationships は中間テーブルなので、usersモデルにネストさせる

end

bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book
  # Favoriteモデルに関連付けを追加する

  validates_uniqueness_of :book_id, scope: :user_id
  # validates_uniqueness_of(検証するフィールド名 [, オプション])
  # book_idとuser_idの一意性をチェックする
  # favoritesテーブルに 同一の組み合わせのbook_idとuser_idがあるかを調べる
end

bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end
end

bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2/app/views/favorites/_favorite-btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
<% end %>
<!-- いいねを送信しているリンクにremote trueを追加する → 「いいね」をクリックするとjs形式のリクエストを送信することができるようになる -->

bookers2/app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
<% end %>
<!-- いいねを送信しているリンクにremote trueを追加する → 「いいね」をクリックするとjs形式のリクエストを送信することができるようになる -->

bookers2/app/views/favorites/cerate.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

bookers2/app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");